name: tflint_tffmt

on: [push]

jobs:
  tflint:
    name: Check terraform files are correct

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main

  tffmt:
    runs-on: ubuntu-latest
    name: Check terraform files are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: terraform
